engines:
  structure:
    enabled: true
    config:
      checks:
          file-lines:
            enabled: true
          argument-count:
            config:
              threshold: 4
          complex-logic:
            config:
              threshold: 4
          method-complexity:
            config:
              threshold: 20
          method-count:
            enabled: true
          method-lines:
            enabled: true
          nested-control-flow:
            config:
              threshold: 4
          similar-code:
            enabled: true
          identical-code:
            enabled: true
          return-statements:
            config:
              threshold: 4
  duplication:
    enabled: false